export const ADDED = "todos/added"
export const TOGGLED = "todos/toggld"
export const COLORSELECTED = "todos/color"
export const DELETED = "todos/delete"
export const COMPLETED = "todos/done"
export const CLEAR = "todos/clear"